# Generated by Django 3.0.5 on 2020-04-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200413_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], null=True),
        ),
    ]
