# Generated by Django 3.0.5 on 2020-04-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'Private'), (1, 'Public')], null=True),
        ),
    ]
