# Generated by Django 3.0.5 on 2020-04-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200418_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='link',
            field=models.URLField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(default='http://glam.nasaharvest.org', upload_to='recipes'),
            preserve_default=False,
        ),
    ]
