# Generated by Django 3.0.5 on 2020-04-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_note_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
