# Generated by Django 3.0.5 on 2020-04-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to='resume/files/%Y/%m/%d/'),
        ),
    ]
