# Generated by Django 3.0.5 on 2020-05-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='since',
            field=models.DateField(blank=True, null=True),
        ),
    ]
