# Generated by Django 3.0.5 on 2020-05-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20200501_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ManyToManyField(to='resume.SkillCategory'),
        ),
    ]
