# Generated by Django 3.0.5 on 2020-05-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20200501_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='employer_logos'),
        ),
    ]
