# Generated by Django 3.0.5 on 2020-05-03 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_employer_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='Job',
            new_name='job',
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField()),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.Job')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Service')),
            ],
        ),
    ]
