# Generated by Django 3.0.5 on 2020-05-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_degree_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='major',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
