# Generated by Django 3.0.5 on 2020-05-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_skillcategory_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=64)),
                ('citation', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('citation', models.TextField()),
                ('date', models.DateField()),
                ('refereed', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='relevant',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
