# Generated by Django 3.0.5 on 2020-04-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='abv',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='rating',
            field=models.IntegerField(choices=[(1, 'OK'), (2, 'Pretty Good'), (3, 'Great')], null=True),
        ),
    ]
