# Generated by Django 3.0.5 on 2020-04-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_auto_20200418_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='brewery',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beer',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='beer',
            name='type',
            field=models.CharField(max_length=32),
        ),
    ]
