# Generated by Django 3.0.5 on 2020-04-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0005_auto_20200418_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='first_time',
            field=models.BooleanField(null=True),
        ),
    ]
