# Generated by Django 3.0.5 on 2020-04-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0008_auto_20200419_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='sub_style',
            field=models.ManyToManyField(blank=True, to='beers.SubStyle'),
        ),
    ]
