# Generated by Django 3.0.5 on 2020-04-19 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0009_auto_20200419_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='sub_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beers.SubStyle'),
        ),
    ]
