# Generated by Django 3.0.5 on 2020-05-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0010_beer_sub_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='added',
            field=models.DateTimeField(),
        ),
    ]
