# Generated by Django 3.0.5 on 2020-05-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0011_auto_20200508_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='date_had',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='added',
            field=models.DateTimeField(editable=False),
        ),
    ]
